# Generated by Django 3.2.7 on 2021-10-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l_data',
            name='Iu',
        ),
        migrations.RemoveField(
            model_name='l_data',
            name='Iv',
        ),
        migrations.RemoveField(
            model_name='l_data',
            name='ru',
        ),
        migrations.RemoveField(
            model_name='l_data',
            name='rv',
        ),
    ]
